#!/bin/bash
sudo sed -i -e 's/^#NAutoVTs=.*$/NAutoVTs=0/' -e 's/^#ReserveVT=.*$/ReserveVT=1/' /etc/systemd/logind.conf \
  || echo -e "\n[Login]\nNAutoVTs=0\nReserveVT=1" | sudo tee -a /etc/systemd/logind.conf

sudo systemctl restart systemd-logind

for i in 2 3 4 5 6; do
  sudo systemctl mask [email protected] 
done

sudo systemctl daemon-reload
